# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  timeout: 5000

development:
  <<: *default
  database: monte-cinema_development

test:
  <<: *default
  database: monte-cinema_test

production:
  <<: *default
